version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}  # API Key as environment variable
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Frontend.Dockerfile
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend  # Ensure backend runs first
    restart: always
